---
- name: install httpd with ansible playbook
  hosts: all
  become: true
  tasks:
#  linux servers
  - name: install httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family=="RedHat"
  - name: start service
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"
#   ubuntu servers
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"
  - name: start service
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"